name: Build UniversalHook

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted   # سينفذ على جهازك الشخصي

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare dependencies
        run: |
          git clone --depth 1 https://github.com/facebook/fishhook.git
          cp fishhook/fishhook.h .
          git clone --depth 1 https://github.com/jmpews/Dobby.git
          cd Dobby && mkdir -p build && cd build
          cmake .. -DDOBBY_GENERATE_SHARED=OFF -DCMAKE_BUILD_TYPE=Release
          make -j$(sysctl -n hw.ncpu)
          cd ../..
          cp Dobby/include/dobby.h .
          cp Dobby/build/libdobby.a .

      - name: Build
        run: |
          clang++ -dynamiclib -std=c++17 -O0 -g \
            -framework Foundation -framework CoreFoundation -framework AppKit \
            -I. -L. -ldobby \
            -o UniversalHook.dylib \
            UniversalHook.mm

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: UniversalHook-macOS
          path: UniversalHook.dylib
